### ISSUE TITLE
RuntimeError in propagation.py from tutorial

### ISSUE THREAD

**Issue by JPBGoe** [PaNOSC-ViNYL/SimEx#122]
[*******]~/simex_tutorial% python propagation.py 
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
initializing ocelot...
Parameters collected
Propagator build
Data read
Starting the backengine
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
initializing ocelot...
################################################################################
Setup initial wavefront.
Load /home/<user>/simex_tutorial/source/3fs_5keV_nz35_0000001.h5
Traceback (most recent call last):
  File "/gpfs/exfel/data/user/<user>/Development/simex_platform/lib/python2.7/SimEx/Calculators/XFELPhotonPropagator.py", line 177, in <module>
    XFELPhotonPropagator.runFromCLI()
  File "/gpfs/exfel/data/user/<user>/Development/simex_platform/lib/python2.7/SimEx/Calculators/AbstractBaseCalculator.py", line 51, in runFromCLI
    status = calculator._run()
  File "/gpfs/exfel/data/user/<user>/Development/simex_platform/lib/python2.7/SimEx/Calculators/XFELPhotonPropagator.py", line 132, in _run
    propagate_s2e.propagate(self.input_path, self.output_path, self.parameters.beamline.get_beamline)
  File "/gpfs/exfel/data/user/<user>/Development/simex_platform/lib/python2.7/prop/propagate_s2e.py", line 127, in propagate
    bl0.propagate(wf)
  File "/gpfs/exfel/data/user/<user>/Development/simex_platform/lib/python2.7/wpg/beamline.py", line 133, in propagate
    srwl.PropagElecField(wfr._srwl_wf, srwl_beamline)
RuntimeError: External (callback) function falied to modify (/ reallocate memory for) wavefront data.

Saving propagated wavefront to /home/<user>/simex_tutorial/prop_out/prop_s2e_example.h5
Saving history.
ALL DONE.
################################################################################
backengine finished
Wave propagation succeeded.

**Comment by CFGrote** [comment]
Fixed in WPG upstream
