### ISSUE TITLE
Tutorial on nano crystal diffraction

### ISSUE THREAD

**Issue by n01r** [PaNOSC-ViNYL/SimEx#158]
Trying the tutorial on [nano-crystal diffraction](https://github.com/eucall-software/simex_platform/wiki/Tutorial-on-nano-crystal-diffraction) and reporting issues.

- importing `CrystFELPhotonDiffractor, CrystFELPhotonDiffractorParameters, PhotonBeamParameters` is not sufficient to create the `beam` variable
- the units are missing due to the upgrade to using the `pint` python package
- [x] fix the imports
- [x] fix the `beam` object with units
- the link to the geometry file is broken
- [x] fix the geometry file link
- creating the `parameters` object throws a warning even though the geometry file exists #159 
- [x] fix the tutorial: constructor of `parameters` object takes `detector_geometry` instead of `geometry`, thanks @belfhi

**Comment by n01r** [comment]
When trying to run the last command `diffr_diagnostics.py -P -p1 -z True xstal_diffr.h5` I am encountering the following error:
```
Traceback (most recent call last):
  File "/data/netapp/s2e/simex/bin/diffr_diagnostics.py", line 25, in <module>
    from SimEx.Analysis.DiffractionAnalysis import DiffractionAnalysis, plt
  File "/data/netapp/s2e/simex/lib/python3.4/SimEx/__init__.py", line 33, in <module>
    from .Analysis.DiffractionAnalysis import DiffractionAnalysis
  File "/data/netapp/s2e/simex/lib/python3.4/SimEx/Analysis/DiffractionAnalysis.py", line 23, in <module>
    from SimEx.Analysis.AbstractAnalysis import AbstractAnalysis, plt, mpl
  File "/data/netapp/s2e/simex/lib/python3.4/SimEx/Analysis/AbstractAnalysis.py", line 32
    class AbstractAnalysis(object, metaclass=ABCMeta):
                                            ^
SyntaxError: invalid syntax
```
That is likely due to the `#!/usr/bin/env python2.7` shebang in the beginning and the python3 branch being installed on Maxwell.

I replaced it by `#!/usr/bin/env python` in the local copy of `diffr_diagnostics.py`  because the `simex` module loads python 3.4 anyway.
`../simex_platform/Sources/python/ScriptCollection/DataAnalysis/scattering/diffr_diagnostics.py -P -p1 -z True xstal_diffr.h5`

```
/usr/lib64/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
initializing ocelot...

WARNING: esther_execute could not be imported. This is most probably due to Esther not being installed or not found. Expect RunTimeErrors when attempting to run the EstherPhotonMatterInteractor.backengine().
WARNING: Giving an operation with a single pattern has no effect.
```
The resulting plot looks like this:
![nanocrystalscatteringplot](https://user-images.githubusercontent.com/5416860/38924254-c3828a6a-42fc-11e8-9233-52f13c352e3b.png)
That's not what it's supposed to look like, according to the tutorial :sweat_smile: 

cc'ing @CFGrote

**Comment by rshopa** [comment]
Same here - looks like detector output contains low statistics, as @n01r noticed. Only 23 non-zero pixels of the same intensity.
![image](https://user-images.githubusercontent.com/15617645/61046875-7905c800-a3de-11e9-91b0-5d20438f2518.png)

**Comment by rshopa** [comment]
UPD: no improvement on diffraction patterns (i.e. few non-zero pixels only) if using files from [SPI tutorial](https://github.com/eucall-software/simex_notebooks/blob/master/start_to_end_demo.ipynb) as input. 

Unfortunately, I've found no way to "feed" CrystFEL (```CrystFELPhotonDiffractorParameters()``` and ```CrystFELPhotonDiffractor()```) with ```pmi_output``` - data with different structure of .h5 file. @CFGrote , is there any way to overcome this problem? I mean - compare the images obtained using SingFEL and CrystFEL after PMI for, say, the same sample ```5udc.pdb```?
