### ISSUE TITLE
SIMEX installation on cluster for Polish XFEL users

### ISSUE THREAD

**Issue by rshopa** [PaNOSC-ViNYL/SimEx#170]
[UPD!] Greetings.

I shall report problems with the basic installation of SIMEX platform on CIŚ cluster (Świerk, Poland https://www.cis.gov.pl/) for Polish XFEL users. 
Since docker is not available (Singularity is announced), it ought to be made manually as described on https://eucall-software.github.io/simex_platform/index.html.

I encountered multiple problems related with dependencies and links to the libraries. Apparently SIMEX requires some with Geant4 and CUDA which is not mentioned in docs. I turned off xcsit as Carsten advised and ran ```install.sh``` with the following options

```
cmake -DSRW_OPTIMIZED=ON \
      -DDEVELOPER_INSTALL=OFF \
      -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
      -DUSE_SingFELPhotonDiffractor=ON \
      -DUSE_CrystFELPhotonDiffractor=ON \
      -DUSE_GAPDPhotonDiffractor=OFF \
      -DUSE_s2e=ON \
      -DUSE_S2EReconstruction_EMC=ON \
      -DUSE_S2EReconstruction_DM=ON \
      -DUSE_wpg=ON \
      -DUSE_GenesisPhotonSource=ON \
      -DUSE_XCSITPhotonDetector=OFF \
      -DUSE_FEFFPhotonInteractor=ON \
      -DXERCESC_ROOT=$XERCESC_ROOT \
      -DGEANT4_ROOT=$GEANT4_ROOT \
      -DXCSIT_ROOT=$XCSIT_ROOT \
      -DBOOST_ROOT=$BOOST_ROOT \
      -DSRW_OPTIMIZED=ON \
      ..
```

What exactly the function of ```GAPDPhotonDiffractor``` is appears a bit unclear to me and it was also turned off, since otherwise a CUDA-related error would erupt:
```
(xfel) [rshopa@wn25107 simex_platform]$ install.sh 
...
-- ***** Including module GAPDPhotonDiffractor from: Diffractors/GAPDPhotonDiffractor ****
-- Found MPI_C: /mnt/home/rshopa/miniconda3/envs/xfel/lib/libmpich.so;/mnt/home/rshopa/miniconda3/envs/xfel/lib/libopa.so;/mnt/home/rshopa/miniconda3/envs/xfel/lib/libmpl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
-- Found MPI_CXX: /mnt/home/rshopa/miniconda3/envs/xfel/lib/libmpichcxx.so;/mnt/home/rshopa/miniconda3/envs/xfel/lib/libmpich.so;/mnt/home/rshopa/miniconda3/envs/xfel/lib/libopa.so;/mnt/home/rshopa/miniconda3/envs/xfel/lib/libmpl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  Modules/Diffractors/GAPDPhotonDiffractor/CMakeLists.txt:5 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/mnt/home/rshopa/SIMEX/simex_platform/build/CMakeFiles/CMakeOutput.log".
```
I also had to set manually paths to FFTW3 library, however, an error occurs while make (related to DM module):

```
(xfel) [rshopa@wn25107 build]$ make     
[ 10%] Built target genesis
[ 20%] Built target ocelot
[ 30%] Built target s2e
[ 31%] Performing build step for 'recon_dm'
object_recon.c:34:19: fatal error: fftw3.h: No such file or directory
compilation terminated.
make[3]: *** [default] Error 1
make[2]: *** [Modules/Analyzers/S2EReconstruction_DM/recon_dm-prefix/src/recon_dm-stamp/recon_dm-build] Error 2
make[1]: *** [Modules/Analyzers/S2EReconstruction_DM/CMakeFiles/recon_dm.dir/all] Error 2
make: *** [all] Error 2
```

Could you provide some hints how to manage these problems?
Thank you in advance for the help.

BTW, I noticed additional issues when using multi-processors (supposedly when creating documantation):

```
(xfel) [rshopa@wn25107 build]$ make -j32
[  1%] [ 10%] Performing build step for 'recon_dm'
Performing install step for 'crystfel'
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
object_recon.c:34:19: fatal error: fftw3.h: No such file or directory
compilation terminated.
make[3]: *** [default] Error 1
make[2]: *** [Modules/Analyzers/S2EReconstruction_DM/recon_dm-prefix/src/recon_dm-stamp/recon_dm-build] Error 2
make[1]: *** [Modules/Analyzers/S2EReconstruction_DM/CMakeFiles/recon_dm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Built target genesis
[ 71%] Built target ocelot
[ 78%] [ 78%] Built target s2e
Built target feff8.5light
[ 80%] Built target recon_emc
[ 81%] Built target wpg
[ 82%] [ 82%] Built target singfel
Built target xraydb
Making install in lib
Making install in doc/reference/libcrystfel
mkdir: cannot create directory `/share': Permission denied
mkdir: cannot create directory `/share': Permission denied
 /usr/bin/install -c -m 644 ./html/CrystFEL-Crystal.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Detector.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-HDF5-file-handling.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Image.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Integer-matrices.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Quaternion.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-RefList-utilities.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-RefList.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Statistics.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Symmetry.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-The-thread-pool.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Unit-cell-utilities.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-UnitCell.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-Utilities.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-coding-standards.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-events.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-filter.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-geometry.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-histogram.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-indexing.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-integration.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-peaks.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-predict-refine.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-render.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL-stream.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/CrystFEL.devhelp2
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/api-index-full.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch01.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch02.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch03.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch04.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch05.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch06.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch07.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch08.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch09.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch10.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch11.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch12.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch13.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch14.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch15.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch16.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch17.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch18.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch19.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch20.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/ch21.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/home.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/index.html
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/left-insensitive.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/left.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/right-insensitive.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/right.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/style.css
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/up-insensitive.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
 /usr/bin/install -c -m 644 ./html/up.png
/usr/bin/install: cannot create regular file `/share/doc/crystfel/reference/libcrystfel/CrystFEL': No such file or directory
Making install in libcrystfel
 /bin/mkdir -p '/lib'
 /bin/mkdir -p '/include/crystfel/'
 /bin/mkdir -p '/lib/pkgconfig'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libcrystfel.la '/lib'
/bin/mkdir: cannot create directory `/include': Permission denied
make[5]: *** [install-libcrystfel_la_includeHEADERS] Error 1
make[5]: *** Waiting for unfinished jobs....
/bin/mkdir: cannot create directory `/lib/pkgconfig': Permission denied
make[5]: *** [install-pkgconfigDATA] Error 1
libtool: install: /usr/bin/install -c .libs/libcrystfel.so.9.0.0 /lib/libcrystfel.so.9.0.0
/usr/bin/install: cannot create regular file `/lib/libcrystfel.so.9.0.0': Permission denied
make[5]: *** [install-libLTLIBRARIES] Error 1
make[4]: *** [install-am] Error 2
make[3]: *** [install-recursive] Error 1
make[2]: *** [Modules/Diffractors/CrystFELPhotonDiffractor/crystfel-prefix/src/crystfel-stamp/crystfel-install] Error 2
make[1]: *** [Modules/Diffractors/CrystFELPhotonDiffractor/CMakeFiles/crystfel.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by CFGrote** [comment]
do you have mkl installed? if yes, make sure to 

    $> source `which compilervars.sh` intel64 


before running cmake (assuming you're on a 64bit architecture). that should then fix the fftw3.h dependency.

c.

**Comment by rshopa** [comment]
As far as I know, MKL is not installed.

**Comment by CFGrote** [comment]
ok, that explains why your issues with fftw3. i have never installed without mkl, so can't really tell much. 

for now, could you deactivate the recon cmake target? there's another dependency on fftw3 (in wpg/srw), but that is handled by the wpg installation makefile and should work even without mkl.

carsten

----- Original Message -----

**Comment by rshopa** [comment]
UPD! Thanks a lot. 

I've already added the whole module ```intel-composer``` (with MKL) and, finally, CUDA (```GAPDPhotonDiffractor=ON```).  The complete list of modules uploaded (some might not be necessary) is as below:
```
(xfel) [rshopa@wn25048 build]$ module list
Currently Loaded Modulefiles:
  1) cis-env                     5) gcc/4.6.3                   9) hdf5/1.8.17.patch1
  2) cis-auto-remove             6) blas/3.5.0-x86_64-gcc46    10) bzip2/1.0.6
  3) cuda/4.2.9                  7) lapack/3.5.0-x86_64-gcc46  11) boost/1.64.0-x86_64-gcc71
  4) binutils/2.22               8) fftw/3.3.4-x86_64-gcc482   12) intel-composer/2016.2.181
```

At first, errors appeared while make, but this was caused by assigning root dir to empty. 
I changed manually ```INSTALL_PREFIX=/mnt/home/rshopa/SIMEX/simex_platform/``` and the installation finally worked out.

BTW, CMake returns a warning -- all these vars were set empty as INSTALL_PREFIX at first. I hope it's not a problem.
```
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    FFTW_INCLUDES
    FFTW_LIBRARIES
    GEANT4_ROOT
    XCSIT_ROOT
    XERCESC_ROOT
```

**Comment by rshopa** [comment]
There's issues on executing Test.py from unittest. Not sure it's an installation issue, but at least a warning of ```Esther``` not being installed is odd
```
(xfel) [rshopa@wn25048 unittest]$ python Test.py -v 2>&1 | tee Test.log
...
WARNING: esther_execute could not be imported. This is most probably due to Esther not being installed or not found. Expect RunTimeErrors when attempting to run the EstherPhotonMatterInteractor.backengine().

WARNING: Importing libpy_detector_interface failed. This is most probably due to XCSIT and/or Geant4 not being installed properly on this system. The XCSITPhotonDetector class can still be instantiated, but the backengine() method will throw an exception.

WARNING: Importing libpy_detector_interface failed. This is most probably due to XCSIT and/or Geant4 not being installed or not being found. Expect errors.
```
There are other errors as follows:
```
...
testBackengineWithPropInput (SimExTest.Calculators.CrystFELPhotonDiffractorTest.CrystFELPhotonDiffractorTest)
Check that beam parameters can be taken from a given propagation output file. ... ERROR
testConstructionWithPropInput (SimExTest.Calculators.CrystFELPhotonDiffractorTest.CrystFELPhotonDiffractorTest)
Check that beam parameters can be taken from a given propagation output file. ... ERROR
...
testBackengine (SimExTest.Calculators.S2EReconstructionTest.S2EReconstructionTest)
Test that we can start a test calculation. ... ERROR
testBackengineDefaultPath (SimExTest.Calculators.S2EReconstructionTest.S2EReconstructionTest)
Test that we can start a test calculation. ... ERROR
testDefaultConstruction (SimExTest.Calculators.S2EReconstructionTest.S2EReconstructionTest)
Testing the default construction of the class. ... ok
testShapedConstruction (SimExTest.Calculators.S2EReconstructionTest.S2EReconstructionTest)
Testing the default construction of the class. ... ok
testBackengine (SimExTest.Calculators.SingFELPhotonDiffractorTest.SingFELPhotonDiffractorTest)
Test that we can start a test calculation. ... Traceback (most recent call last):
  File "/mnt/home/rshopa/SIMEX/simex_platform/bin/radiationDamageMPI", line 9, in <module>
    main(parameters=parameters)
  File "/mnt/home/rshopa/SIMEX/simex_platform/lib/python3.6/pysingfel/radiationDamageMPI.py", line 26, in main
    slave_diffract(comm, parameters)
  File "/mnt/home/rshopa/SIMEX/simex_platform/lib/python3.6/pysingfel/radiationDamageMPI.py", line 94, in slave_diffract
    MakeOneDiffr(myQuaternions, counter, parameters, outputName)
  File "/mnt/home/rshopa/SIMEX/simex_platform/lib/python3.6/pysingfel/radiationDamage.py", line 160, in MakeOneDiffr
    particle = Particle(inputName, datasetname)
  File "/mnt/home/rshopa/SIMEX/simex_platform/lib/python3.6/pysingfel/particle.py", line 38, in __init__
    self.readh5File(fname[0], fname[1])
  File "/mnt/home/rshopa/SIMEX/simex_platform/lib/python3.6/pysingfel/particle.py", line 56, in readh5File
    with h5py.File(fname, 'r') as f:
  File "/mnt/home/rshopa/miniconda3/envs/xfel/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/mnt/home/rshopa/miniconda3/envs/xfel/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```
The program freezes at this moment (liable only to be broken) - is this just about long simulation time or due to errors?

**Comment by CFGrote** [comment]
can you make sure that Tests/python/unittest/TestFiles/pmi_out_0000001.h5 exists?

if not, you're probably missing git-lfs. please check https://help.github.com/en/articles/versioning-large-files.

c
