### ISSUE TITLE
Error for multiple node computing

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/SimEx#207]
```
/gpfs/exfel/data/user/juncheng/miniconda3/condabin/conda
/home/juncheng/.conda/envs/simex/bin/python
No Modulefiles Currently Loaded.
initializing ocelot...

WARNING: esther_execute could not be imported. This is most probably due to Esther not being installed or not found. Expect RunTimeErrors when attempting to run the EstherPhotonMatterInteractor.backengine().
Traceback (most recent call last):
  File "/home/juncheng/.conda/envs/simex/lib/python3.6/SimEx/Utilities/ParallelUtilities.py", line 58, in _getParallelResourceInfoFromSlurm
    ncores+=int(cores)*int(mul)
ValueError: invalid literal for int() with base 10: 'x2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "diffr_test.py", line 75, in <module>
    diffractor.backengine()
  File "/home/juncheng/.conda/envs/simex/lib/python3.6/SimEx/Calculators/SingFELPhotonDiffractor.py", line 184, in backengine
    np, ncores = self.computeNTasks()
  File "/home/juncheng/.conda/envs/simex/lib/python3.6/SimEx/Calculators/SingFELPhotonDiffractor.py", line 132, in computeNTasks
    resources = ParallelUtilities.getParallelResourceInfo()
  File "/home/juncheng/.conda/envs/simex/lib/python3.6/SimEx/Utilities/ParallelUtilities.py", line 114, in getParallelResourceInfo
    return _getParallelResourceInfoFromSlurm()
  File "/home/juncheng/.conda/envs/simex/lib/python3.6/SimEx/Utilities/ParallelUtilities.py", line 64, in _getParallelResourceInfoFromSlurm
    raise IOError( "Cannot use SLURM_JOB_NUM_NODES and/or SLURM_JOB_CPUS_PER_NODE. Set SIMEX_NNODES and SIMEX_NCORES instead")
OSError: Cannot use SLURM_JOB_NUM_NODES and/or SLURM_JOB_CPUS_PER_NODE. Set SIMEX_NNODES and SIMEX_NCORES instead

```

**Comment by JunCEEE** [comment]
72(x2)
['72(x2)']
7 x2
