### ISSUE TITLE
XMDYNPhotonMatterInteractorTest error

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/SimEx#223]
```
======================================================================
ERROR: testBackengineMultipleProp (__main__.XMDYNPhotonMatterInteractorTest)
Check that the backengine method works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "XMDYNPhotonMatterInteractorTest.py", line 174, in testBackengineMultipleProp
    status = test_interactor.backengine()
  File "/gpfs/exfel/data/user/juncheng/simex-branch/Sources/python/SimEx/Calculators/XMDYNPhotonMatterInteractor.py", line 233, in backengine
    ' --pmi_params ' + \
  File "/gpfs/exfel/data/user/juncheng/miniconda3/envs/simex-branch/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'XMDYNANDXATOMDBPATH'
```

**Comment by CFGrote** [comment]
you have to set than environment variable to point to a directory than holds your dbase
