### ISSUE TITLE
The wpg saved h5 file is not correct as the input of the next run?

### ISSUE THREAD

**Issue by jnl0517** [PaNOSC-ViNYL/SimEx#51]
I run the simex with wpg method and had a error. The details of error are following.

"
###### 
# Starting SIMEX photon-matter interaction.
###### 

Previous module:  small_size_large_detector
  NOT: data
  NOT: history
misc
params
version
[u'arrEhor', u'arrEver']
[(u'arrEhor', <HDF5 dataset "arrEhor": shape (101, 101, 550, 2), type "<f4">), (u'arrEver', <HDF5 dataset "arrEver": shape (101, 101, 550, 2), type "<f4">)]

Traceback (most recent call last):
  File "PhotonExperimentSimulationTest.py", line 44, in <module>
    pxs.run()
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/SimEx/PhotonExperimentSimulation/PhotonExperimentSimulation.py", line 161, in run
    self.__photon_interactor.backengine()
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/SimEx/Calculators/XMDYNDemoPhotonMatterInteractor.py", line 190, in backengine
    pmi_demo.f_load_pulse( pmi_demo.g_s2e['prop_out'] )
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/pmi_demo.py", line 260, in f_load_pulse
    self.g_s2e['pulse']['xFWHM']   = xfp.get( '/misc/xFWHM' )   .value
AttributeError: 'NoneType' object has no attribute 'value'
[liujin@exflst314]~/0609_run/9keV/small_size_large_detector% python PhotonExperimentSimulationTest.py > a.txt
Traceback (most recent call last):
  File "PhotonExperimentSimulationTest.py", line 44, in <module>
    pxs.run()
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/SimEx/PhotonExperimentSimulation/PhotonExperimentSimulation.py", line 161, in run
    self.__photon_interactor.backengine()
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/SimEx/Calculators/XMDYNDemoPhotonMatterInteractor.py", line 190, in backengine
    pmi_demo.f_load_pulse( pmi_demo.g_s2e['prop_out'] )
  File "/afs/desy.de/user/l/liujin/SIMEX/v0.1/lib/python2.7/pmi_demo.py", line 260, in f_load_pulse
    self.g_s2e['pulse']['xFWHM']   = xfp.get( '/misc/xFWHM' )   .value
AttributeError: 'NoneType' object has no attribute 'value'
"

The original code is in the directory test in branch xrt_calculator

**Comment by CFGrote** [comment]
Probably related to #39 but I'll check

**Comment by jnl0517** [comment]
I may find the reason. The PropagateSE.py of prop has the same problem and it is solved by adding some more information into the output file H5.

**Comment by jnl0517** [comment]
I add some code about information into backengine of the Waveprogator.py as PropagateSE dose and it works.
